name: Build and Sign APK

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: init android openssl
        run: ./init-android-openssl

      - name: init android
        run: ./init-android

      - name: download ndk
        run: wget https://dl.google.com/android/repository/android-ndk-r14b-linux-x86_64.zip && unzip ./android-ndk-r14b-linux-x86_64.zip && echo "NDK_ROOT=$(pwd)/android-ndk-r14b" >> $GITHUB_ENV

      - name: compile openssl
        run: ./compile-openssl.sh clean && ./compile-openssl.sh arm64
        working-directory: android/contrib
        env: 
          ANDROID_NDK: ${{ env.NDK_ROOT }}

      - name: Upload so
        uses: actions/upload-artifact@v2
        with:
          name: crypto
          path: android/contrib/build/openssl-arm64/output/lib/libcrypto.so
          