name: Build and Sign APK

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: init android openssl
        run: ./init-android-openssl.sh

      - name: init android
        run: ./init-android.sh

      - name: download ndk
        run: wget https://dl.google.com/android/repository/android-ndk-r10e-linux-x86_64.zip && unzip ./android-ndk-r10e-linux-x86_64.zip && echo "NDK_ROOT=$(pwd)/android-ndk-r10e" >> $GITHUB_ENV

      - name: compile openssl
        run: ./compile-openssl.sh clean && ./compile-openssl.sh arm64
        working-directory: android/contrib
        env: 
          ANDROID_NDK: ${{ env.NDK_ROOT }}
          ANDROID_NDK_ROOT: ${{ env.NDK_ROOT }}

      - name: compile ffmpeg
        run: ./compile-ffmpeg.sh clean && ./compile-ffmpeg.sh arm64
        working-directory: android/contrib
        env: 
          ANDROID_NDK: ${{ env.NDK_ROOT }}
          ANDROID_NDK_ROOT: ${{ env.NDK_ROOT }}

      - name: compile ijk-player
        run: ./compile-ijk.sh arm64
        working-directory: android
        env: 
          ANDROID_NDK: ${{ env.NDK_ROOT }}
          ANDROID_NDK_ROOT: ${{ env.NDK_ROOT }}

      - name: copy openssl library
        run: mkdir -p android/ijkplayer/openssl-lib/src/main/jniLibs/arm64-v8a && cp android/contrib/build/openssl-arm64/output/lib/*.so android/ijkplayer/openssl-lib/src/main/jniLibs/arm64-v8a

      - name: build library
        run: chmod +x ./gradlew && ./gradlew :ijkplayer-arm64:assembleRelease
        working-directory: android/ijkplayer
        env: 
          ANDROID_NDK: ${{ env.NDK_ROOT }}
          ANDROID_NDK_ROOT: ${{ env.NDK_ROOT }}

      - name: Upload output
        uses: actions/upload-artifact@v2
        with:
          name: ijkplayer-arm64-output
          path: android/ijkplayer/ijkplayer-arm64/build/outputs

      - name: assemble openssl library
        run: chmod +x ./gradlew && ./gradlew :openssl-lib:assembleRelease
        working-directory: android/ijkplayer
        env: 
          ANDROID_NDK: ${{ env.NDK_ROOT }}
          ANDROID_NDK_ROOT: ${{ env.NDK_ROOT }}

      - name: Upload output
        uses: actions/upload-artifact@v2
        with:
          name: openssl-arm64-output
          path: android/ijkplayer/openssl-lib/build/outputs

      - name: build java library
        run: chmod +x ./gradlew && ./gradlew :ijkplayer-java:assembleRelease
        working-directory: android/ijkplayer
        env: 
          ANDROID_NDK: ${{ env.NDK_ROOT }}
          ANDROID_NDK_ROOT: ${{ env.NDK_ROOT }}
      
      - name: Upload output
        uses: actions/upload-artifact@v2
        with:
          name: ijkplayer-java-output
          path: android/ijkplayer/ijkplayer-java/build/outputs


          